name: Moderasi + Approval Giscus
on:
  discussion_comment:
    types: [created]

jobs:
  moderate_and_approve:
    runs-on: ubuntu-latest
    steps:
      - name: Moderasi komentar
        uses: actions/github-script@v6
        with:
          script: |
            const badWords = ["spamword", "iklan", "kata kasar"];
            const body = context.payload.comment.body.toLowerCase();
            const discussion_id = context.payload.discussion.id;
            const comment_id = context.payload.comment.id;

            // 1. Lock dulu discussion (sementara)
            await github.graphql(`
              mutation($discussion_id: ID!) {
                lockLockable(input: {lockableId: $discussion_id, lockReason: RESOLVED}) {
                  lockedRecord {
                    id
                  }
                }
              }
            `, { discussion_id: discussion_id });

            console.log("Discussion dikunci untuk approval.");

            // 2. Cek apakah komentar mengandung kata terlarang
            if (badWords.some(word => body.includes(word))) {
              console.log("Komentar mengandung kata terlarang. Menghapus...");
              await github.rest.discussions.deleteComment({
                discussion_comment_id: comment_id,
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              return;
            }

            // 3. Jika lolos, unlock kembali discussion
            await github.graphql(`
              mutation($discussion_id: ID!) {
                unlockLockable(input: {lockableId: $discussion_id}) {
                  unlockedRecord {
                    id
                  }
                }
              }
            `, { discussion_id: discussion_id });

            console.log("Komentar aman, discussion dibuka kembali.");
