name: Moderasi Manual

on:
  discussion_comment:
    types: [created]

permissions:
  discussions: write

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - name: Check Discussion Comment for Moderation
        uses: actions/github-script@v7
        with:
          script: |
            const commentBody = context.payload.comment.body;
            const matchDelete = commentBody.match(/DELETE:(\d+)/i);
            const matchApprove = commentBody.match(/APPROVE:(\d+)/i);

            if(matchDelete) {
              const comment_id = parseInt(matchDelete[1]);
              console.log(`Detected DELETE on comment ID: ${comment_id}`);

              // Hapus komentar di discussion
              await github.rest.discussions.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                discussion_comment_id: comment_id
              });

            } else if(matchApprove) {
              const comment_id = parseInt(matchApprove[1]);
              console.log(`Detected APPROVE on comment ID: ${comment_id}`);

              // Catat approve, bisa notify Telegram atau log saja
              console.log(`Comment approved: ${comment_id}`);
            } else {
              console.log("No moderation command found in this discussion comment.");
            }
        with:
          script: |
            // Jika perlu unlock discussion atau catat approve
            console.log("Comment approved: ${{ github.event.inputs.comment_id }}");
