name: Aksi Moderasi Giscus

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'approve atau delete'
        required: true
      discussion_number:
        description: 'Nomor diskusi (untuk approve)'
        required: false
      comment_id:
        description: 'ID komentar'
        required: true

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Lakukan Aksi
        uses: actions/github-script@v7
        with:
          script: |
            const action = "${{ github.event.inputs.action }}";
            const discussion_number = parseInt("${{ github.event.inputs.discussion_number }}");
            const comment_id = parseInt("${{ github.event.inputs.comment_id }}");

            if (action === "approve") {
              await github.rest.discussions.unlock({
                discussion_number,
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              console.log(`✅ Approved discussion ${discussion_number}`);
            } else if (action === "delete") {
              await github.rest.discussionComments.deleteComment({
                discussion_comment_id: comment_id,
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              console.log(`❌ Deleted comment ${comment_id}`);
            } else {
              console.log("⚠️ Aksi tidak dikenal:", action);
            }
